### ISSUE TITLE
Migration mechanism

### ISSUE THREAD

**Issue by emig** [eHealthAfrica/eha-couch-migrations#5]
I like the way Rails has a migrations folder with timestamped migration files. In that case the files define a schema transformation. In our case the file would be the data migration itself.

The migration script should keep track of the migrations (saving the latest migration applied?)
In order to apply only the new migrations.

**Comment by jo** [comment]
A difference to Rails is that here we are modifying data where in Rails normally only the schema gets changed by migrations. And in Rails migrations are run one time because there is generally only one master database. In our scenario we run migrations simultanely. That way I think its best to store migration state on a per document basis.

Since we already store schema versions in the document, this could be used to determine which migration needs to be run. See https://github.com/eHealthAfrica/model-discussion/issues/4 for the rough conzept @janl and me had in mind.

**Comment by emig** [comment]
@jo thanks for making it clear.
